name: llama2
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pip
  # PyTorch >= 2.1 (so you never hit that import_utils / LOSS_MAPPING issue)
  - pytorch>=2.1.0
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio

  # FSDP / distributed / quant libs
  - accelerate
  - bitsandbytes
  - sentencepiece        # prebuilt wheel, no C++ compile
  - safetensors

  # LoRA / adapters
  - pip
  - pip:
      - git+https://github.com/huggingface/peft.git
      - openai==0.28.0
      - trl
      - shortuuid

  # Transformers & datasets
  - transformers>=4.31.0
  - datasets

  # Safety evaluation & plotting
  # - openai
  - fire
  - matplotlib
  - pandas
  - tqdm
  - protobuf=3.20.3

  # Utilities
  - appdirs
  - py7zr
  - scipy
  - optimum

  # Formatting
  - black
  - black-jupyter  # for notebook formatting

  # HTTP charset sniffing (silence Requests warnings)
  - chardet
  - charset-normalizer

  # HF Hub support
  - huggingface_hub
  - packaging
